### ISSUE TITLE
PyPI package

### ISSUE THREAD

**Issue by kellrott** [FHIR-Aggregator/client#4]
Setup PyPI package to enable pip install

**Comment by bwalsh** [comment]
Should be there already at: https://pypi.org/project/fhir-aggregator/0.2rc1/

**Comment by bwalsh** [comment]
I'll ensure it is in the documentation

**Comment by bwalsh** [comment]
resolved here: https://github.com/FHIR-Aggregator/client/pull/3/commits/10504110eb2454eefd79802afdc32fdcfff27f5e
